# Generated by Django 6.0.1 on 2026-01-29 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nome')),
                ('unit', models.CharField(choices=[('m', 'Metro'), ('un', 'Unidade'), ('hr', 'Hora')], default='un', max_length=10, verbose_name='Unidade')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço unitário')),
                ('is_service', models.BooleanField(default=True, verbose_name='É serviço?')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
        ),
    ]
