# Generated by Django 6.0.1 on 2026-01-29 20:23

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('sent', 'Enviado'), ('approved', 'Aprovado'), ('canceled', 'Cancelado')], default='draft', max_length=20, verbose_name='Status')),
                ('discount_type', models.CharField(choices=[('none', 'Sem desconto'), ('fixed', 'Desconto em R$'), ('percent', 'Desconto em %')], default='none', max_length=20, verbose_name='Tipo de desconto')),
                ('discount_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Valor do desconto')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('public_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token público')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='crm.customer')),
            ],
        ),
        migrations.CreateModel(
            name='QuoteLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Descrição (opcional)')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, verbose_name='Quantidade')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço unitário')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.catalogitem')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='quotes.quote')),
            ],
        ),
    ]
